language: node_js
node_js:
  - 6
  - 10

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  matrix:
    - SECRET_VAR2=SECRET2
    - SECRET_VAR2=SECRET3
    - SECRET_VAR2=SECRET4

matrix:
  allow_failures:
    - env: SECRET_VAR2=SECRET2
      node_js: 10

before_install:
  - npm config set spin false

script:
  - npm run lint:js
  - npm test
